apiVersion: v2
name: platform
description: Umbrella chart dla platformy DevSecOps AutoHealKube
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus
    version: "25.0.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.0"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: loki-stack
    version: "2.9.0"
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: falco
    version: "2.0.0"
    repository: https://falcosecurity.github.io/charts
    condition: falco.enabled
  - name: kyverno
    version: "3.0.0"
    repository: https://kyverno.github.io/kyverno/
    condition: kyverno.enabled
